//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CFPPE.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class alumnos
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public alumnos()
        {
            this.actividadesa = new HashSet<actividadesa>();
            this.archivoprealum = new HashSet<archivoprealum>();
            this.calificacion = new HashSet<calificacion>();
            this.libretamochalum = new HashSet<libretamochalum>();
            this.padretutor = new HashSet<padretutor>();
            this.archivodocalum = new HashSet<archivodocalum>();
            this.tareas = new HashSet<tareas>();
        }
    
        public int idAlumno { get; set; }
        public int idInscripcion { get; set; }
        public int idUser { get; set; }
        public int idMateria { get; set; }
        public int idMaestro { get; set; }
        public string NombreA { get; set; }
        public string APP { get; set; }
        public string APM { get; set; }
        public string Sexo { get; set; }
        public string Direccion { get; set; }
        public string Correo { get; set; }
        public string Telefono { get; set; }
        public int Grado { get; set; }
        public string Grupo { get; set; }
        public string Status { get; set; }
        public string CodigoM { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<actividadesa> actividadesa { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<archivoprealum> archivoprealum { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<calificacion> calificacion { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<libretamochalum> libretamochalum { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<padretutor> padretutor { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<archivodocalum> archivodocalum { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tareas> tareas { get; set; }
        public virtual inscripcion inscripcion { get; set; }
        public virtual maestros maestros { get; set; }
        public virtual materia materia { get; set; }
        public virtual usuario usuario { get; set; }
    }
}
