//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CFPPE.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class inscripcion
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public inscripcion()
        {
            this.alumnos = new HashSet<alumnos>();
        }
    
        public int idInscripcion { get; set; }
        public string NombreA { get; set; }
        public System.DateTime FechaNac { get; set; }
        public System.DateTime FechaInscripcion { get; set; }
        public int Edad { get; set; }
        public int Seccion { get; set; }
        public int Grado { get; set; }
        public string Grupo { get; set; }
        public string AlergiasEnfermedad { get; set; }
        public string Observacion { get; set; }
        public string NombreT { get; set; }
        public string Ocupacion { get; set; }
        public string Direccion { get; set; }
        public string TelCasa { get; set; }
        public string TelTrabajo { get; set; }
        public string TelCeluar { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<alumnos> alumnos { get; set; }
    }
}
