//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CFPPE.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class materia
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public materia()
        {
            this.actividadesa = new HashSet<actividadesa>();
            this.alumnos = new HashSet<alumnos>();
            this.calificacion = new HashSet<calificacion>();
            this.maestros1 = new HashSet<maestros>();
            this.tareas = new HashSet<tareas>();
        }
    
        public int idMateria { get; set; }
        public int idSeccion { get; set; }
        public int idMaestro { get; set; }
        public string Materia1 { get; set; }
        public string CodigoM { get; set; }
        public System.DateTime FechaIN { get; set; }
        public System.DateTime FechaFI { get; set; }
        public string Descripcion { get; set; }
        public int Status { get; set; }
        public int Grado { get; set; }
        public string Grupo { get; set; }
        public int idTipoM { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<actividadesa> actividadesa { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<alumnos> alumnos { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<calificacion> calificacion { get; set; }
        public virtual maestros maestros { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<maestros> maestros1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tareas> tareas { get; set; }
        public virtual seccion seccion { get; set; }
    }
}
