//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CFPPE.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class padretutor
    {
        public int idPadre { get; set; }
        public int idUser { get; set; }
        public int idAlumno { get; set; }
        public string NombreT { get; set; }
        public string APP { get; set; }
        public string APM { get; set; }
        public string Sexo { get; set; }
        public string Direccion { get; set; }
        public string Correo { get; set; }
        public string TelCasa { get; set; }
        public string TelTrabajo { get; set; }
        public string TelCel { get; set; }
    
        public virtual alumnos alumnos { get; set; }
        public virtual usuario usuario { get; set; }
    }
}
